import { Project } from "@/lib/types";

export const projects: Project[] = [
  {
    id: "momo-runner",
    title: "Momo Runner Game",
    description: "An infinite runner game built from scratch with custom gameplay mechanics",
    longDescription: "Built during summer 2021, this infinite runner game demonstrates end-to-end game development from concept to implementation. Features strategic tradeoffs within fast-paced gameplay - use the left arrow to run, right arrow to stop, and space bar to throw shiruken. The game introduces novel mechanics that add depth to the traditional infinite runner formula.",
    technologies: ["Game Maker Language", "GameMaker Studio 2", "Game Design"],
    imageUrl: "/images/projects/momo-runner.jpg",
    githubUrl: "https://github.com/ashersebban/MomoRunnerGame",
    featured: true,
  },
  {
    id: "processing-canvas",
    title: "Processing Canvas",
    description: "An interactive creative coding project and one of my favorite early works",
    longDescription: "My first major project in Processing, this interactive canvas showcases creative coding and visual design. It represents the beginning of my journey into building interactive experiences and remains one of my favorite projects for its blend of art and code.",
    technologies: ["Processing", "Creative Coding", "Visual Design"],
    imageUrl: "/images/projects/processing-canvas.jpg",
    githubUrl: "https://github.com/ashersebban/ProcessingCanvas",
    featured: true,
  },
  {
    id: "flappy-bird",
    title: "Flappy Bird Game",
    description: "A recreation of the classic Flappy Bird game built on Processing",
    longDescription: "A faithful recreation of the viral Flappy Bird game, built entirely in Processing. This project demonstrates understanding of game physics, collision detection, and creating engaging gameplay loops. A great exercise in implementing well-known game mechanics from scratch.",
    technologies: ["Processing", "Game Development"],
    imageUrl: "/images/projects/flappy-bird.jpg",
    githubUrl: "https://github.com/ashersebban/FlappyBirdGame",
    featured: true,
  },
  {
    id: "database-management",
    title: "Database Design & Management",
    description: "Comprehensive coursework in database design and SQL (Course grade: A)",
    longDescription: "Academic project showcasing proficiency in database design principles, SQL query optimization, and data management. Covers database normalization, complex queries, indexing strategies, and best practices for efficient data storage and retrieval.",
    technologies: ["SQL", "Database Design", "HTML"],
    imageUrl: "/images/projects/database.jpg",
    githubUrl: "https://github.com/ashersebban/DB-Design-and-Mgmnt",
    featured: false,
  },
  {
    id: "green-design",
    title: "Green Design Website",
    description: "A web design project focused on sustainable and eco-friendly design principles",
    longDescription: "A website exploring green design principles and sustainable web development practices. This project combines HTML, CSS, and thoughtful UX to create an environmentally-conscious web experience.",
    technologies: ["HTML", "CSS", "Web Design"],
    imageUrl: "/images/projects/green-design.jpg",
    githubUrl: "https://github.com/ashersebban/GreenDesignWebsite",
    featured: false,
  },
  {
    id: "cs101",
    title: "CS101 Projects",
    description: "Collection of foundational computer science projects in Java",
    longDescription: "A collection of projects from my introductory computer science course, demonstrating fundamental programming concepts, data structures, and algorithms in Java. These projects laid the foundation for my technical skills and problem-solving approach.",
    technologies: ["Java", "Data Structures", "Algorithms"],
    imageUrl: "/images/projects/cs101.jpg",
    githubUrl: "https://github.com/ashersebban/CS101",
    featured: false,
  },
  {
    id: "fishtank-screensaver",
    title: "Fishtank Screen Saver",
    description: "A relaxing cartoon fishtank and bubbles screensaver made in Processing",
    longDescription: "A simple but charming screensaver featuring cartoon fish and bubbles. This project explores animation, random movement, and creating calming visual experiences through code.",
    technologies: ["Processing", "Animation", "Visual Design"],
    imageUrl: "/images/projects/fishtank.jpg",
    githubUrl: "https://github.com/ashersebban/FishtankScreenSaver",
    featured: false,
  },
];
