// Portfolio project data: used by the Projects page and ProjectCard
import { Project } from "@/lib/types";

export const projects: Project[] = [

  // ---- GAMES ----
  {
    id: "processing-canvas",
    title: "Processing Canvas",
    description: "A modern drawing studio with pen/eraser, palettes, zoom, undo/redo, and export built from my original Processing sketch.",
    longDescription: "I rebuilt my original Processing canvas into a full drawing app that feels closer to a creative tool than a demo. It showcases real-time pointer input, pressure-aware strokes, responsive canvas scaling, undo/redo history, palette systems, and export flow in a polished single-page experience.",
    technologies: ["Processing", "Creative Coding", "Visual Design"],
    category: "app",
    language: "Processing",
    imageUrl: "/images/projects/processing-canvas.jpg",
    githubUrl: "https://github.com/ashsebban/ProcessingCanvas",
    demoUrl: "/games/processing-canvas/index.html",
  },
  {
    id: "flappy-bird",
    title: "Flappy Bird",
    description: "A faithful recreation of the viral Flappy Bird — tap to flap, survive the pipes.",
    longDescription: "A faithful recreation of the viral Flappy Bird game, built entirely in Processing. This project demonstrates understanding of game physics, collision detection, and creating engaging gameplay loops. A great exercise in implementing well-known game mechanics from scratch.",
    technologies: ["Processing", "Game Development"],
    category: "game",
    language: "Processing",
    imageUrl: "/images/projects/flappy-bird.jpg",
    githubUrl: "https://github.com/ashsebban/FlappyBirdGame",
    demoUrl: "/games/flappy-bird/index.html",
  },
  {
    id: "fishtank-screensaver",
    title: "Mind-Clearing Ocean",
    description: "An interactive ocean meditation: relax with ambient fish, tap to declutter, or run a guided breathing session that clears the scene.",
    longDescription: "This evolved from a simple screensaver into an intentional interactive mindfulness piece. It combines tail-driven fish motion, subtle ocean animation, responsive touch/mouse interaction, and mode-based UX. Users can stay in calm relax mode, actively declutter by tapping fish away, or use a timed breathing flow to clear mental noise.",
    technologies: ["Processing", "Animation", "Creative Coding"],
    category: "game",
    language: "Processing",
    imageUrl: "/images/projects/fishtank.jpg",
    githubUrl: "https://github.com/ashsebban/FishtankScreenSaver",
    demoUrl: "/games/fishtank/index.html",
  },
  {
    id: "shape-runner",
    title: "Shape Runner",
    description: "A 3-in-1 shape-switch runner: flappy-style circle, grid-style square, and ninjump-style triangle in one continuous run.",
    longDescription: "Originally built as my CS101 final project in Java, Shape Runner is a side-scrolling obstacle game where you cycle between three movement systems mid-run. Circle uses flappy-like gravity and jump timing, Square snaps across discrete layers, and Triangle flips between top and bottom lanes in a ninjump-style rhythm. Obstacles rotate between three blocker families, and survival depends on matching the right shape to the right color: green for circle, blue for square, and red for triangle.",
    technologies: ["Java", "Game Design", "OOP"],
    category: "game",
    language: "Java",
    imageUrl: "/images/projects/cs101.jpg",
    githubUrl: "https://github.com/ashsebban/CS101",
    demoUrl: "/games/cs101-game/index.html",
  },
  {
    id: "momo-runner",
    title: "Momo Runner",
    description: "An infinite runner built in GameMaker — run, stop, and throw shurikens to survive.",
    longDescription: "Built during summer 2021, this infinite runner game demonstrates end-to-end game development from concept to implementation. Features strategic tradeoffs within fast-paced gameplay — use the left arrow to run, right arrow to stop, and space bar to throw shurikens. The game introduces novel mechanics that add depth to the traditional infinite runner formula.",
    technologies: ["GameMaker Studio 2", "GML", "Game Design"],
    category: "game",
    language: "GML",
    imageUrl: "/images/projects/momo-runner.jpg",
    githubUrl: "https://github.com/ashsebban/MomoRunnerGame",
  },

  // ---- WEBSITES ----
  {
    id: "green-design",
    title: "Green Design Website",
    description: "A multi-page Bootstrap site exploring sustainable and eco-friendly design principles.",
    longDescription: "A website exploring green design principles and sustainable web development practices. This project combines HTML, CSS, and thoughtful UX to create an environmentally-conscious web experience across multiple pages.",
    technologies: ["HTML", "CSS", "Bootstrap", "Web Design"],
    category: "website",
    imageUrl: "/images/projects/green-design.jpg",
    githubUrl: "https://github.com/ashsebban/GreenDesignWebsite",
    demoUrl: "https://ashsebban.github.io/GreenDesignWebsite/sites/home/",
  },
  {
    id: "db-site",
    title: "Database Design Portfolio Site",
    description: "A personal course site built for NYU's Database Design & Web Implementation class.",
    longDescription: "A multi-page HTML/CSS site built to document and present coursework from NYU's Database Design and Web Implementation course. Includes a home page with personal bio, and a coursework section linking to individual homework projects including SQL work, Python data scripts, and the chess opening database.",
    technologies: ["HTML", "CSS", "Web Design"],
    category: "website",
    imageUrl: "/images/projects/database.jpg",
    githubUrl: "https://github.com/ashsebban/DB-Design-and-Mgmnt",
    demoUrl: "https://ashsebban.github.io/DB-Design-and-Mgmnt/DB_Site/Home/",
  },

  // ---- APPS ----
  {
    id: "in-between",
    title: "In Between",
    description: "A job fit scorer — upload your resume, paste a job description, and get a keyword match score with gaps highlighted.",
    longDescription: "A Next.js app built to cut through the noise in job searching. Upload your resume as a .txt or .md file, enter your preferences and a job description, and the app scores how well your resume matches the role using keyword frequency analysis. Shows matched and missing keywords, and helps you decide which jobs are actually worth applying to. Built with Next.js App Router, TypeScript, and a custom scoring algorithm.",
    technologies: ["Next.js", "TypeScript", "API Routes"],
    category: "app",
    language: "TypeScript",
    imageUrl: "/images/projects/cs101.jpg",
    githubUrl: "https://github.com/ashsebban/in-between",
    liveUrl: "https://in-between-phi.vercel.app",
  },
  {
    id: "chess-opening-db",
    title: "Chess Opening Database",
    description: "A Python + SQL app that filters thousands of real chess games by opening and underdog status.",
    longDescription: "Built for NYU's Database Design course. A chess analytics tool where users select an opening (e.g. Sicilian Defense, Ruy Lopez) and filter for 'underdog' wins — games where a lower-rated player beat a higher-rated one. Queries a SQLite database of thousands of real online chess matches via a Python CGI backend. A practical exercise in database design, SQL queries, and data-driven web interfaces.",
    technologies: ["Python", "SQL", "SQLite", "HTML", "CGI"],
    category: "app",
    language: "Python/SQL",
    imageUrl: "/images/projects/database.jpg",
    githubUrl: "https://github.com/ashsebban/DB-Design-and-Mgmnt",
  },
  {
    id: "fractal-tree",
    title: "Fractal Tree Generator",
    description: "A recursive Java program that renders a self-similar fractal tree.",
    longDescription: "Built as a debugging exercise in CS101, this Java program uses recursive binary branching to render a fractal tree. Each branch splits into two smaller branches at an angle, continuing until the branches are too small to render. A visual demonstration of recursion and tree data structures in action.",
    technologies: ["Java", "Recursion", "Computer Science"],
    category: "app",
    language: "Java",
    imageUrl: "/images/projects/cs101.jpg",
    githubUrl: "https://github.com/ashsebban/CS101",
  },
];
